[project]
name = "landfall"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "user", email = "user@email" }
]
requires-python = ">=3.14"
dependencies = [
    "pysimplegui>=6.3.0.1",
    "requests>=2.34.2",
]

[project.scripts]
landfall = "landfall:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
